"""empty message

Revision ID: 2c44524d110b
Revises: ffdc0a98111c
Create Date: 2022-02-14 21:39:15.634198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c44524d110b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('travel_speed', sa.DECIMAL(), nullable=False),
    sa.Column('minimum_per_map', sa.Integer(), nullable=True),
    sa.Column('maximum_per_map', sa.Integer(), nullable=True),
    sa.Column('is_crossable', sa.Boolean(), nullable=True),
    sa.Column('is_origin_feature', sa.Boolean(), nullable=True),
    sa.Column('is_destination_feature', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_latitude', sa.Integer(), nullable=False),
    sa.Column('start_longitude', sa.Integer(), nullable=False),
    sa.Column('stop_latitude', sa.Integer(), nullable=False),
    sa.Column('stop_longitude', sa.Integer(), nullable=False),
    sa.Column('feature_type_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_type_id'], ['feature_types.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('maps')
    op.drop_table('feature_types')
    # ### end Alembic commands ###
